[project]
authors = ["Edouard Duchesnay <edouard.duchesnay@cea.fr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pystatsml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipython = "*"
scipy = "*"
numpy = "*"
pandas = ">=2.0.3"
openpyxl = "*"
jupyter = "*"
matplotlib = "*"
scikit-learn = ">=1.3.0"
seaborn = "*"
statsmodels = ">=0.14.0"
numdifftools = "*"
nltk = "*"
wordcloud = "*"
torchvision = "*"
skorch = "*"
pandoc = "*"
sphinx-gallery = "*"
nbstripout = "*"

[pypi-dependencies]
docxbuilder = { version = "*", extras = ["math"] }
semopy = { version = "*"}
